word_bank = [
["gentleman", "nobleman", "noblemen", "lord", "baron", "baronet", "peer", "marquis", "marquess", "earl", "viscount", "count"],
["lady", "ladies", "gentlewoman", "baroness", "baronesses", "peeress", "peeresses", "duchess", "duchesses", "viscountess", "viscountesses", "countess", "countesses"],
["politician", "candidate", "MP", "statesman", "statesmen", "lawmaker"],
["lawyer", "solicitor", "judge", "attorney", "magistrate", "barrister"],
["banker", "moneylender", "exchanger"],
["beadle", "curate", "parson", "rector", "vicar", "priest", "pastor"],
["captain", "general", "colonel", "sergeant"],
["doctor", "physician", "surgeon", "medic", "doc"],
["soldier", "recruit", "conscript", "infantry", "infantryman", "footsoldier"],
["grocer", "businessman", "manager", "businessperson", "merchant"],
["clerk", "secretary", "assistant"],
["policeman", "policemen", "constable", "detective", "peeler", "bobby", "bobbies"],
["schoolmaster", "schoolteacher", "teacher"],
["student", "novice", "apprentice", "disciple", "scholar", "pupil"],
["ostler", "innkeeper"],
["tailor", "couturier", "costumier"],
["craftsman", "potter", "carpenter", "toymaker", "cobbler", "mason", "stonemason", "blacksmith"],
["seamstress", "seamstresses"],
["servant", "manservant", "coachman", "butler", "footman", "grooms", "houseboys", "housemen", "men", "menservants", "servitors", "valets"],
["nurse", "nursemaid"],
["governess", "governesses"],
["maid", "maidservant", "housekeeper", "handmaid", "handmaiden", "cook", "charwoman"],
["farmer", "rancher"],
["waiter", "dash", "barman", "barmen", "aproner"],
["fisherman", "fishermen", "fishmonger"],
["costermonger", "peddlar"],
["washerwoman", "washerwomen", "laundress", "laundresses"],
["navvy", "navvies", "navvie"],
["miner", "pitman", "digger"],
["nightman", "nightmen"],
["orphan", "urchin"],
["thief", "swindler", "conman", "crook", "pickpocket", "criminal"]]


word_categories = ["gentleman", "lady", "politician", "lawyer", "banker",
"clergyman", "military (high rank)", "doctor", "soldier", "businessman",
"clerk", "policeman", "schoolteacher", "student", "innkeeper", "tailor",
"craftsman", "seamstress", "male servant", "nurse", "governess",
"female servant", "farmer", "waiter", "fisherman", "street peddlar",
"washerwoman", "navvy", "miner", "nightman", "orphan", "criminal"]