word_bank = [["lawyer", "solicitor", "judge", "attorney", "magistrate", "barrister"],
["nurse", "nursemaid"],
["maid", "maidservant", "housekeeper", "handmaid", "handmaiden", "cook", "charwoman"],
["tailor"],
["governess"],
["clerk"],
["craftsman", "potter", "carpenter", "toymaker", "cobbler", "mason" "stonemason", "blacksmith"],
["grocer", "businessman", "manager", "businessperson", "merchant"],
["costermonger", "peddlar"],
["orphan", "urchin"],
["servant", "manservant", "coachman", "butler", "footman", "grooms", "houseboys", "housemen", "majordomos", "men", "menservants", "servitors", "valets"],
["banker", "moneylender"],
["thief", "swindler", "conman"],
["navvy", "navvies", "navvie"],
["nightman", "nightmen"],
["farmer"],
["ostler", "innkeeper"],
["miner", "pitman", "digger"],
["waiter", "dash", "barman", "barmen", "aproner"],
["beadle", "curate", "parson", "rector", "vicar"],
["clerk", "assistant"],
["washerwoman"],
["governess"],
["student"],
["doctor", "physician", "surgeon"],
["soldier"],
["captain", "general", "colonel", "sergeant"],
["policeman", "policemen", "constable", "detective", "peeler", "bobby", "bobbies"],
["fisherman", "fishermen"],
["schoolmaster", "schoolteacher", "teacher"],
["politician", "candidate"]]